apiVersion: apps/v1
kind: Deployment
metadata:
  name: used-book
  namespace: usedbook-prod
  labels:
    app: used-book
    project: used-book
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: used-book
  template:
    metadata:
      labels:
        app: used-book
        project: used-book
        environment: prod
    spec:
      containers:
      - name: used-book
        image: used-book:prod
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: usedbook
        - name: PORT
          value: "8080"
        - name: ALADIN_TTB_KEY
          valueFrom:
            secretKeyRef:
              name: aladin-ttb-key
              key: ttbkey
              optional: true
        ports:
        - containerPort: 8080
