apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: usedbook-prod
commonLabels:
  project: used-book
  environment: prod
resources:
  - namespace.yaml
  - used-book.yaml
  - used-book-svc.yaml
  - postgres.yaml
  - ingress.yaml
images:
- name: used-book
  newTag: git-41c24a0
