apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: used-book-prod
  namespace: argocd
spec:
  destination:
    namespace: usedbook-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/prod
    repoURL: https://github.com/abyss-works/used-book
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
